### ISSUE TITLE
bug: 롤링페이퍼 추가 모달 X 버튼 위치

### ISSUE THREAD

**Issue by yeodahui** [Rolling-Paper-Project/Rolling-Page#100]
![image](https://user-images.githubusercontent.com/102221305/184125777-ae1aa198-ab4c-4c3d-ad59-d8697d477f6a.png)
X버튼이 의도하시지 않은 곳에 있는 것 같습니다 :- )

환경:
윈도우 데스크탑
Chrome 브라우저

**Comment by Iam-Ujin** [comment]
와우 다희님 깃헙까지 찾아와서 피드백 주시다니 감사합니다!
